---

- hosts: all
  become: yes
  tasks:
  - name: Ubuntu Install Apache 
    apt:
      name=apache2
      state=latest
    when:
      ansible_os_family == "Debian"
    notify:
      - web systemd apache2
  handlers:
    - name: web systemd apache2
      systemd:
        name: apache2
        enabled: yes
        state: started
