---

- hosts: all
  become: yes
  tasks:
  - name: Ubuntu Install Nginx
    apt:
      name=nginx
      state=latest
    when:
      ansible_os_family == "Debian"
    notify:
      - web systemd
  handlers:
    - name: web systemd
      systemd:
        name: nginx
        enabled: yes
        state: started
